apiVersion: v1
kind: Service
metadata:
  labels:
    app: green
  name: green
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: green
  type: NodePort
status:
  loadBalancer: {}