apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: green
  name: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green
  strategy: {}
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: green
        image: gcr.io/k8s-proj-1/echo-color
        env:
        - name: COLOR
          value: green
        ports:
        - name: tcp
          containerPort: 8080
        resources: {}
status: {}
